### ISSUE TITLE
请问作者multi-scale test是怎么实现的呢？

### ISSUE THREAD

**Issue by sumaliqinghua** [lxg2015/notes#1]
用不同的大小测试然后将结果取平均就可以了吗，怎样对齐呢？
非常感谢您的回答~

**Comment by lxg2015** [comment]
多尺度测试可以参看大佬写的[box_vote](https://github.com/sfzhang15/SFD/blob/c1abcf014d430354ce3a61c7f33de0dcf2021186/sfd_test_code/WIDER_FACE/wider_test.py#L84)，就是在NMS结果上根据置信度做加权。
